### ISSUE TITLE
似乎缺少这一篇

### ISSUE THREAD

**Issue by xell** [MindFxck/daguguguji#17]
流传颇广，只是似乎特师自己删掉了，找不到原始微博。

长话短说，阿姨抱拳，六点半我正在阳台远眺，大家都知道我住3000平米大平层。
天气很好，通透，远处天际线飞机忙忙碌碌，金星闪烁，四环堵的一塌糊涂，两条线，一红一黄，由于led大灯流行，黄色列亮度很高，很白，这样看起来像是一红一白，

要回老家了，抱歉！阿姨颔首，接下来的职责不能履行，万分抱歉，说完阿姨土下座了，我说，怎么讲，说说，
回老家了，房子不让住了，阿姨说，找不到住的地方，
原来是这样！我说，那也没有办法，没住的地方确实只好回老家了一刚，我说，回去好好建设家乡，记得一定要买房，没自己的房，家就像浮萍一样，说散就散
老家有房子的呀，阿姨说，还是想呆在北京，儿子工作这下也完蛋了，孙子还想在北京上学，现在看也不行了，只好去别处看看，老家总归不能回的，先去南京看看吧，上南师大也是好的
想多了！我说，南师大想上就上吗，哈刚把刚，阿姨突然站起来！走到阳台上远眺，阿姨说，你看，这城市璀璨，远处是北方，多少高楼大厦，一颗一颗窗户，忽明忽暗，城市的眼睛啊，现在逐渐都闭上了，你看四环，川流不息，像动脉，我从老家来，想要添砖加瓦，现在要回去
回去也不错，我说，走到哪里都需要，为人民服务，，为人民币服务，呵呵，劳动永远最光荣，劳动人永远最光荣，
广阔天地大有作为！我说
再见！阿姨抱拳，走了，桌上留下门禁，钥匙，各种卡，我走到阳台，远处灯火辉煌，社会主义进入新阶段，红色横幅不断，无数的住宅楼窗户忽明忽暗，又怎样，不是你亮就是我亮，不是东方压倒西风，就是西风压倒东方，你方唱罢我登场，能见度很好，看见国贸，三里屯盈通，四环川流不息，这时想起的歌曲是美空川の流れのように，崔健，荣光或是什么，流弹打中胸膛，最后，刹那，又在想，什么是永远，我宁愿你冷酷到底，羽泉，打开窗，地暖热的要死，右手从秋裤上方伸进去，握住几把，几把冰凉。想起微博上看见人们吵吵，人民，什么的，后来又说，同胞，什么的，突然想起来，现在什么样算是同胞，我们的同胞又是什么人，有没有同胞，昨天半夜刷微博突然看见某狗逼落马的消息，先是高兴，后来又萎了，突然想起来，阳痿十几年，都忘了吃药这件事，右手从秋裤裆部开口伸进去，永远是冰凉冰凉的一团，分不清哪是龟头哪是卵泡，冰凉一片。2008年初，长桥，电视塔下，藏书羊肉还没开店，大家都知道火车站要拆了，盖高铁站，伟大的工程要建三百年，却不知道一场大雪就要来。

**Comment by naoyeye** [comment]
伟大！收藏了！蟹蟹
