### ISSUE TITLE
为什么我新增了几个 markdown 文件在gitbook serve之后没有显示在导航栏里

### ISSUE THREAD

**Issue by LiuWenJia-ops** [MindFxck/daguguguji#32]
如题

**Comment by naoyeye** [comment]
抱歉回复迟了。

我看到在代码合并之后，导航栏中已经显示了新增的文章。

<img width="223" alt="image" src="https://github.com/MindFxck/daguguguji/assets/434428/86d132ba-e32e-43ef-9a53-33ba37b02fa1">
